<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@page language="java" contentType="text/html; charset=UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<!DOCTYPE html>
<html>
<head>
<jsp:include page="head.jsp" />
<title>Downloads</title>
</head>
<body>
	<jsp:include page="header.jsp" />
		<div class="jumbotron">
			<h2>Batch Downloads</h2>
			<blockquote><p>
				Data files below are auto-generated from the integrated BioPAX database. 
				They are sorted alphabetically and generally named as follows:</p>
				<code>${cpath.name}.${cpath.version}.&lt;SOURCE&gt;.&lt;FORMAT&gt;.&lt;ext&gt;.gz</code>
				<p>(Other versions can be downloaded from <a href="${cpath.url}">${cpath.name}</a> archives.)</p>
			</blockquote>
			<em>&lt;SOURCE&gt;</em> is a standard name, taxonomy ID, or 'All'<br/>
			<em>&lt;FORMAT&gt;</em> is one of the <a href="formats">Output Formats</a><br/> 
			<em>&lt;ext&gt;</em> is the file type.
		</div>
		
		<h3>Notes</h3>
		<ul>
			<li>Each archive by source or organism is generated by searching for all BioPAX Entities 
				associated with the given organism or data source and making a new BioPAX sub-model, 
				which is then converted to other formats.</li>
			<li><strong>*Detailed_Process_Data*</strong> are generated using the BioPAX data sources 
				only (i.e, excluding those converted from PSI-MI format).</li>				
			<li>blacklist.txt is used by the BioPAX to SIF and SBGN converters to exclude ubiquitous small molecules from output. 
				See <a href="http://code.google.com/p/biopax-pattern/wiki/UsingBinaryInteractionFramework#Blacklisting_ubiquitous_small_molecules" 
				target="_blank">blacklist.txt file description</a> for more information.</li>
			<li>datasources.txt provides metadata and some statistics about each data source.</li>				
			<li>Full <a rel="nofollow" href='<c:url value="/validations"/>'>BioPAX validation reports</a> 
				(XML and HTML formatted) are available for each data source loaded into the system  
				(can be useful to data providers to help check the accuracy of their data).</li>
			<li>Original data files used to build this system <a rel="nofollow" href='<c:url value="/datadir"/>'>are available</a> 
				at various intermediate states: after cleaning, conversion, normalization and before merging.</li>
			<li>We could also provide custom conversion to SIF formats (e.g., using extra columns, 
				selected interaction types, data sources and ID type) by request; 
				or one can do it with the <a href="http://www.biopax.org/paxtools">Paxtools</a> 
				using one of the BioPAX archives as input and blacklist.txt (to ignore ubiquitous small molecules).</li>				
		</ul>
		
		<h3>Files</h3>
		<ul>
			<c:forEach var="f" items="${files}">
				<li><a rel="nofollow" href='<c:url value="/downloads/${f.key}"/>'>${f.key}</a>&nbsp;(${f.value})</li>
			</c:forEach>
		</ul>

	<jsp:include page="footer.jsp" />
</body>
</html>
