User-agent: *
Disallow: /get
Disallow: /graph
Disallow: /search
Disallow: /traverse
Disallow: /idmapping
Disallow: /metadata/
Disallow: /admin/
Disallow: /downloads/
Disallow: /help/
Disallow: /top_pathways
