package cpath.dao.internal.filters;

import org.biopax.paxtools.model.level3.Dna;
import org.biopax.paxtools.model.level3.DnaRegion;
import org.biopax.paxtools.model.level3.Protein;
import org.biopax.paxtools.model.level3.Entity;

import cpath.dao.filters.SearchFilterRange;


/**
 * Defines a filter by organism for entities,
 * i.e.: {@link Protein},  {@link Dna}, {@link DnaRegion}, etc.
 * This filter uses organism relationship xrefs auto-generated by 
 * the BioPAX normalizer.
 * 
 * 
 * @author rodche
 *
 */
@SearchFilterRange(Entity.class)
public class EntityByOrganismRelationshipXrefsFilter 
	extends SearchFilterAdapter<Entity, String> 
{

	@Override
	public boolean apply(Entity searchResult) {
		// TODO use relationship xrefs with rel. CV "ORGANISM"; compare 'id' vs. the list of filter values
		return false;
	}

}
