package cpath.dao.internal.filters;

import java.util.Set;

import org.biopax.paxtools.controller.ModelUtils;
import org.biopax.paxtools.controller.ModelUtils.RelationshipType;
import org.biopax.paxtools.model.level3.ControlledVocabulary;
import org.biopax.paxtools.model.level3.Dna;
import org.biopax.paxtools.model.level3.DnaRegion;
import org.biopax.paxtools.model.level3.Protein;
import org.biopax.paxtools.model.level3.Entity;
import org.biopax.paxtools.model.level3.RelationshipXref;
import org.biopax.paxtools.model.level3.Xref;
import org.biopax.paxtools.util.ClassFilterSet;

import cpath.dao.filters.SearchFilterRange;


/**
 * Defines a filter by organism for entities,
 * i.e.: {@link Protein},  {@link Dna}, {@link DnaRegion}, etc.
 * This filter uses organism relationship xrefs auto-generated by 
 * the BioPAX normalizer.
 * 
 * 
 * @author rodche
 *
 */
@SearchFilterRange(Entity.class)
public class EntityByProcessRelationshipXrefsFilter 
	extends SearchFilterAdapter<Entity, String> 
{

	@Override
	public boolean apply(Entity searchResult) {
		if(values.isEmpty())
			return true;
		
		Set<RelationshipXref> rxrefs = new ClassFilterSet<Xref, RelationshipXref>(
				searchResult.getXref(), RelationshipXref.class);
		for(RelationshipXref rx : rxrefs) {
			ControlledVocabulary rcv = rx.getRelationshipType();
			if(rcv != null 
				&& rcv.getTerm().contains(RelationshipType.PROCESS.name())
				&& this.values.contains(rx.getId())) // by design, the value is a Process URI (RDF ID) 
			{
				assert ModelUtils.COMMENT_FOR_GENERATED.equals(rx.getDb()) : "Only rel. xrefs auto-generated "
					+ "by the normalizer can be used in this filter implementation. Such rel. xrefs have "
					+ " property db=" + ModelUtils.COMMENT_FOR_GENERATED + ", and id - URI of the corresponding "
					+ "Process (Pathway or Interaction) object in the same model.";
				return true;
			}
		}
		
		return false;
	}

}
